### PR TITLE
Update Repo2docker Requirement

### PR DESCRIPTION
**Pull request by salvis2**
Remove the requirement for repo2docker. See #43 .

### CODE REVIEW

**Comment by yuvipanda** [comment]
There has been a new repo2docker release! https://pypi.org/project/jupyter-repo2docker/ - 0.11. Let's change our requirement?

**Comment by salvis2** [comment]
Yeah I'll try using that and see if everything works.

**Comment by salvis2** [comment]
I confirmed that repo2docker v0.10 still wasn't able to push an image because of the error above, then confirmed that v0.11 worked. Now we can have clean requirements again!

**Comment by salvis2** [comment]
I had to update the cache "version" on my fork to get the setuptools to solve correctly.

**Comment by yuvipanda** [comment]
@salvis2 right. I removed the 'fall back to latest cache' functionality, which seems to have made things much better!

**Pull request merged**
