### PR TITLE
Document the hubploy workflow a little better

### PR DESCRIPTION
**Pull request by yuvipanda**
- Document the deployment process with a flowchart
- Document components of hubploy workflow
- Document known limitations of hubploy

### CODE REVIEW

**Comment by consideRatio** [comment]
Excellent summary, very useful to me! Im looking forward to see the rendered RST!

**Comment by yuvipanda** [comment]
@consideRatio you are very sweet, has anyone told you that?

**Comment by consideRatio** [comment]
@yuvipanda yes you have :) :heart:

Lots of love from Sweden, hope you are well!

**Comment by yuvipanda** [comment]
@consideRatio roller coaster, but good to hear from you more :) 

https://hubploy.readthedocs.io/en/latest/ is the rendered version, looks good!

**Comment by consideRatio** [comment]
@yuvipanda likewise!

Excellent example use of generating a flowchart like this! I want to make these kinds of flowcharts as well going onwards. I'm am still afraid of RST in general though, I'm scarred from moments struggling with getting a development setup working with RST involved.

**Comment by consideRatio** [comment]
https://mermaid-js.github.io/mermaid/#/ omg nice!

**Comment by consideRatio** [comment]
Ah!

[](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgICBZdXZpICYgRXJpayAtLT4gRXJpa1xuICAgIFl1dmkgJiBFcmlrIC0tPiAubWQgXG4gICAgLm1kIC0tIDpPIC0tPiAucnN0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Pull request merged**
