### PR TITLE
Use key names from service principal commands in Azure

### PR DESCRIPTION
**Pull request by yuvipanda**
This uses the keys in the JSON file created by the
`az ad sp` command here as well, instead of making our own.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@tjcrone what do you think of this change?

**Comment by tjcrone** [comment]
I think it makes a lot more sense to use these key names. Great! Will the ruamel parser read this JSON file as is? Or will that need to be adjusted as well? Probably worth noting though that the `az ad sp` command can include `--output yaml` to output a YAML file instead, which I think is a tad more readable. See: https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest.

**Comment by yuvipanda** [comment]
@tjcrone ah, all valid JSON is valid YAML, so it should work just fine...

**Comment by tjcrone** [comment]
Great! Well, I think the key names you have chosen are much better since they are the ones generated by the Azure CLI. I am ready to merge this whenever you are. Thanks!

**Comment by yuvipanda** [comment]
Thanks, @tjcrone!

**Pull request merged**
