### PR TITLE
Support decrypting secrets from sops

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by consideRatio** [comment]
Nice!!! Ill use and test this soon!

**Comment by consideRatio** [comment]
Nice work @yuvipanda! I've succesfully built and pushed to GCP storage with a gcr-key.json in my secrets folder configured like this.

```yaml
images:
  image_name: us.gcr.io/neurohackademy/nh-2020-env
  registry:
    provider: gcloud
    gcloud:
      project: neurohackademy
      service_key: gcr-key.json
```

The file `gcr-key.json` is sops-encrypted by `sops -e --in-place secrets/gcr-key.json` and is looking like this on disk:

```json
{
	"type": "ENC[AES256_GCM,data:WIxy4RgSqQzKVw6X0YLF,iv:lQv8Zpzjll+mWYnJ9KD/rxN5unPPEmGrZQBTXDyGtSs=,tag:RbF3yfmL5yKzT/lu8/4wFw==,type:str]",
	"project_id": "ENC[AES256_GCM,data:iluA+AQWBB37lVQ8PZU=,iv:bd95t5ltJV5eyK88g01yp+CtHykjAaOrl97dPx+NG40=,tag:pFgGQBaRmVfhya304cg2OQ==,type:str]",
	"private_key_id": "ENC[AES256_GCM,data:MpL/V7+E/Ipq58MfIArT+AUBwuzdrY4MDhE8SspdkR0pBImI92cbiQ==,iv:jyHMy+1jVLB4JOxdIHHDudQQeViYeeQZAq5h9cX+xPA=,tag:qDtzS2FHATzYfZ9/i7z1Ww==,type:str]",
	"private_key": "ENC[AES256_GCM,data:yEqwfPCc34KN0Rszllsy5/Tcso/L4SYhACcZOkj9xDkD4wNt2hIvACmhyY4lIWBTpn8BjOCWbBPK+zDLdtZPHIAGjalo0TpURPZiRqIqP/Fbn9HGC5wg+8XxSsExkFtucQP4qu3igoaAQAsZvPooHQD1HIjXOia4/mDuaQm1qu/HIczStmILJLXayKcKtcX9dGrebsjGy9WLAVPZiJMmZrZ1Te3cwdgL3AEujoG4sPzXogHXGTcUfQaQZSOzCtyklSBD1bNblCE5+mBr05sgmM5cX3qAubCYBXQ9A5/A3nkrBTaGcOzKmXFOP4MSgBzr9qVqZzOsNLNtSLrzJPzaSguxA4qcMXXa+f9nWnAsC8MAXmYHIvEfhUc61BxP8RlWxR1Ot9mj4ZpxqxGyhrh8hoV8aKSLgQfPyUrxFeG6K0vyNofHWeF434vnMN9wuIUZ4Ms2f7EcJe11dn4zpJdQakin2YJg60hLt7ueST8dJicGkQpdoavj2k0/Xwuhk4SiQDOJ29Rlv7Xf9ncYCEnT8BuIzXAMg/dUqvueG6SQmR1v+dAHRH9XLcFBf1OTX8F69GPTepWoQsYBokm29vuZ1n8Z33SILD/eAFWmzY7wTCIIQDh4kMAxYKeTXOaRK/HL6ZIoMNbNKzyEjvMxsQ3sZzsCEaLFbyuBiHUZS+lFfyv1LjZ97j2/3xmcDhwyHRnwgJAtSrn8PHE2Neg5RGr34ph4XapG69ctKgaeLS/9b6fKN84I59rMjQfRZ8egNdbxn5Wvd5RAOzTR5xcsd/6qlKwlyAUUxHYMw/Au6M05JYy1WUem2PIaEAaESG5KTIS4hSD4EtmhrrLir4bytGeFKmYsnmox9zwNTfNnGVX1ucX8Wy6G9YB89VgVfBjo4EA+r55y7ALW0SNwrB+d+2ixkwgnwZg8YjLylqzrFkLqpKV6tOmIv0AozBj0bKHLFDKBkLUqYubad7YE9le3x9FyhiFf8PV1qjUJkE9WuRrkCCZWNmKJRTLQI8v9F6hbJV7Wv9T6UUSrw8I08M1yQ11vyDX6ggWzROrx2+YUt4ZlehqPFpsXTHBfmtub9JP5+uOa//34aPKjt+by7aDbAffT2j8ziJs8IFU48mBaQIIFy+F9nruj4p4cS+oeSVSxd+DB2lwtRKRMVi1J5vuPbgoNUiVX6MZpf/m+ZGijnCIAIWAOPlgtBecVEQItPKed79+VBQCEEc6zWKLqk+B+jKLg9w2pJ0rDaVQ7YOIQlwx5Dvyx+jD8V8JZAXLa3UMeImuXrhRi8v2R12GwPG4iAMxubbi50tyDDI++3roTYZMpUOq7VFao6ud4HX2FPORYHKaJO5QEUetiqM38h0zy0mMuFzoK2HyXWJNwnPx8lKyIQQKrZBTlU0E28QPh4zykIO1cxc40U9HbHF8K9weGT8r7tWWE0aWpjinG3g/RpJdL2IVRWbam2pAdRz4YiDkTyF84mMF+LcWwAc0BrLEhVJBwDGfUjY9KOxMYLbwPHeAcLZDYg35nJIKKTu1oQqsKllSURKJQY7EQ3/2qQO8JUKO9vyJI6FjlUifdEHKdwxCNa/R9DC5ut7df099XS+/kD11W6BIUjOV7yHo5+asiQdNSDTzHH3uuEkaWl6+lsAi/hh4tQLjtjj1pqKpQPKYsYQDR7hYKtVWb2RkVgcht0OYJI3Zpi/pz/7U/XSHXEKQo5c5rfc3BizzeKJe7TZzCSjIopn4q3PiAgH+x1NAw1pv4HNkfU9qHpIJORXL4D/ViSH4dTxF6TIm/iXifgu5W0LGC39iLWSPaUiNVDCVZoprwK5hJgqhYfggaIZ3CZPCXZTIbVPOQl/RVmdXeB2UxmFDN4YAWyxugvHhaCKQQMcwutdeL2DNRcylG2qFGbppoN5Pq0rF4tR3qwziFlZmdSmUUJ0Rf0Lg+EWVFttW+LxKxBsug7j6wnikcyoqkrsAZlFXCla/kmOqysUfxbEDoVIa+k30Y9jFtDZQ3+1SMG+hwiVNRrEHz1sdsPc/p7tN981goMInfHqPFUi4S5iGpSzWO9a7ccKSEn7Cmfd2VOS9Tb5Vo0Y5ZvtectXqfsmXRz9m7PGYhzZ/rkdjgDBnbuJyJYHPJAawbACG2K6mjVut4Fcb3erkU9XENbEhhz/4LpdAidw8UdcJ/jCq9a6XWXwcObyXGvSO7SWkJv8MXSFfV4rY9h08q66TyUnpBMQ/cuprHlieHeyjPSd3l9PzWJb9+ylLFG0t4c0OMwzWGcyCSVuEKcj6FF4EC,iv:e313sK7sPKxBvELivbqrDFOYM1AaawNf7DoItE7mv6E=,tag:R4wgvh5DqpBY/e1xYQ+w+g==,type:str]",
	"client_email": "ENC[AES256_GCM,data:C2I+YZ3YFnm8JE23otQpt24bCVqzQdzOWcVRRoQY9N5KVDVbZIYyCEQbcZdXC6F+7Go=,iv:HoDEjWCBRSJUHBWWCSvh+bXNlL1Z3FVzQj5FK1/MC6w=,tag:VFKXEEq4LCmZDQ6+HFQo0g==,type:str]",
	"client_id": "ENC[AES256_GCM,data:5suvIPcycwd3kAwKY9YdpbchnnqN,iv:Pamszlr4Ja8XHQiZqmVX9Vhl3YIMg9rLIKaYf/LqQ28=,tag:wfYNXws2bIOGIJOby5x12Q==,type:str]",
	"auth_uri": "ENC[AES256_GCM,data:5FiWRscgl6VAaEpTSKhecmdBbu5SSQ2+PvpYyVXOIQ3NO2xogHS+yOg=,iv:YzSqzCygkt8BSCS/CNuLt2mLw79MDDNasc9qRknkbfs=,tag:NjsTTvRQciLG8DzthLRmwg==,type:str]",
	"token_uri": "ENC[AES256_GCM,data:ton8XOG8na1UFn+gKqyFwFfBvPOrOcdWtMiq1IyAM9zF8cA=,iv:abA7oEwHR161ZIaCLhB9KwJ9pLjfJ+xtcqFdeg1hIgY=,tag:5XT7CY0LPUQFpsyy43BS3w==,type:str]",
	"auth_provider_x509_cert_url": "ENC[AES256_GCM,data:bK+HRJdxwvEDCtp+rkA0rpcCvb/sBxeN298nh95yuxrD35pcBwuzYcii,iv:j4Yi5W6/+wmBEEozl7fDpR1Wh5vama/9rHF/6B2yYjU=,tag:AjRzLeKzGsieE4D6Ry9Jlg==,type:str]",
	"client_x509_cert_url": "ENC[AES256_GCM,data:9ZHHVrxC+bDFiWAL6JaLqFX0fGkERF9iW5FNbNms4Yf2pKPN8tpNmvBmTPpgjsW5+XFDT148pGGdSrHCbDmKVciDmJKlBwhsBSncxvjldgEcySY7UMPseDiuV7Evj3IESd/23Xu3,iv:vtdHVmGpXBe3N59EbwGj9oTaNXujvksWyO0iBB1MfH8=,tag:9E23bd7YCzOGBJBTccwzUg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": [
			{
				"resource_id": "projects/neurohackademy/locations/global/keyRings/nh-2020/cryptoKeys/main",
				"created_at": "2020-06-27T11:40:43Z",
				"enc": "CiQAPiFjYRDFKo7xDFdu94WyDNyzKIxGwCMX+VtmA3gZKhrFx/USSQBLOy9hMF+kdmapmF0sc3RgzRqbCwo+M2BWlWp19pfWoKEAU0mrGBwEI4WMqzVnj1IbzcWTjzxQdayQ+XJ9Bu6hxUgkrDkQIAM="
			}
		],
		"azure_kv": null,
		"lastmodified": "2020-06-27T11:40:43Z",
		"mac": "ENC[AES256_GCM,data:ATqFIQmtZIHeavon11LvTGQD5CaeK3HrEvnbeglrYlD9+NVSpSvvNEgbbeenu0RJ+5hkRnskEOn0rPVAPgcg0FX4yDqmzAd6rxMgG4i6PQlbY5T2xUXgCPUwFTUazqmnWsyeiq7XwPnn459DJDXrDd65uWAgoezhYWl99cX69Eo=,iv:CoKR9NhGJtVWV/DPHuDnfYuBD3hCC6UpIcWTmnRY28g=,tag:MDDDH4qL/meXle4L7ui3Jg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.5.0"
	}
}
```

**Comment by yuvipanda** [comment]
Awesome, @consideRatio! Thank you very much for testing this :D I'm gonna merge this now.

**Comment by consideRatio** [comment]
Wieee! :D

**Pull request merged**
